### ISSUE TITLE
Improve visualization

### ISSUE THREAD

**Issue by gonanda** [gonanda/Data-Ninja-Places-to-open-a-Japanese-restaurant#1]
I would like to improve the visualization of this project. I would like to improve my plots using big labels and different colors. Anyone would like to collaborate with me?

**Comment by KC2016** [comment]
Fernanda, segundo o curso q fiz, o recomendado para esse tipo de graficos é de manter a mesma cor para cada categoria, pq cores podem enganar a percepcao do analista/leitor do seu projeto. Acho que faz bastante sentido.
